---
sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - pip install pipenv
install: pipenv install --deploy --system
script: molecule test
notifications:
  email: true
  on_success: change
  on_failure: always
